# Porta do Servidor Web (Login e Listas)
server.port=8080

# Conexão automática com o MySQL (Cria o banco de dados caso não exista)
spring.datasource.url=jdbc:mysql://localhost:3306/ddtank_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=01030907Ll$

# Dialeto do Hibernate adaptado para otimizar queries do MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect